{{- if and (not .Values.existingConfigmap) .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ephemeral-envs.fullname" . }}-config
  labels:
    {{- include "ephemeral-envs.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
{{- end -}}
